---
product-name: harbor-container-registry
product-properties:
  .harbor-app.static_ips:
    value: ((harbor_static_ip))
  .properties.admin_password:
    value:
      secret: ((opsman_user.password))
  .properties.admin_password_for_smoketest:
    value:
      secret: ((opsman_user.password)) 
  .properties.auth_mode:
    selected_option: db_auth
    value: db_auth
  .properties.customize_container_network:
    selected_option: default
    value: default
  .properties.hostname:
    value: ((harbor_fqdn))
  .properties.initial_delay_minutes:
    value: 60
  .properties.log_insight:
    selected_option: disabled
    value: disabled
  .properties.no_proxy:
    value: 127.0.0.1,localhost,.local,.internal,log,db,redis,nginx,core,portal,postgresql,jobservice,registry,registryctl,clair-adapter,chartmuseum,notary-server
  .properties.registry_storage:
    selected_option: filesystem
    value: filesystem
  .properties.server_cert_ca:
    value: ((harbor_cert.ca))
  .properties.server_cert_key:
    value:
      cert_pem: ((harbor_cert.certificate))
      private_key_pem: ((harbor_cert.private_key))
  .properties.trivy_skip_update:
    value: false
  .properties.vm_monitor:
    selected_option: no_monitor
    value: no_monitor
  .properties.with_notary:
    value: true
  .properties.with_trivy:
    value: true
network-properties:
  network:
    name: ((networks_infrastructure))
  other_availability_zones:
  - name: ((availability_zone))
  singleton_availability_zone:
    name: ((availability_zone))
resource-config:
  harbor-app:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: automatic
    nsx:
      lbs: []
      security_groups: []
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
  smoke-testing:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: automatic
    nsx:
      lbs: []
      security_groups: []
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    swap_as_percent_of_memory_size: automatic
errand-config:
  smoke-testing:
    post-deploy-state: when-changed
  uaa-deregistration:
    pre-delete-state: false

