---
product-name: credhub-service-broker
product-properties:
  .properties.allow_paid_service_plans:
    value: false
  .properties.apply_open_security_group:
    value: false
  .properties.credhub_broker_enable_global_access_to_plans:
    value: true
  .properties.org:
    value: credhub-service-broker-org
  .properties.space:
    value: credhub-service-broker-space
network-properties:
  network:
    name: ((networks_services))
  other_availability_zones:
  - name: ((availability_zone))3
  - name: ((availability_zone))2
  - name: ((availability_zone))1
  singleton_availability_zone:
    name: ((availability_zone))1
resource-config:
  delete-all:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: automatic
    nsx:
      lbs: []
      security_groups: []
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    swap_as_percent_of_memory_size: automatic
  deploy-all:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: automatic
    nsx:
      lbs: []
      security_groups: []
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    swap_as_percent_of_memory_size: automatic
errand-config:
  delete-all:
    pre-delete-state: true
  deploy-all:
    post-deploy-state: true