---
product-name: p-rabbitmq
product-properties:
  .on-demand-broker.canaries:
    value: 1
  .on-demand-broker.global_service_instance_quota:
    value: 20
  .on-demand-broker.max_in_flight:
    value: 3
  .properties.enable_inter_node_tls:
    value: false
  .properties.enable_tls_selector:
    selected_option: disabled
    value: disabled
  .properties.global_settings_force_cluster_shutdown_on_version_change:
    value: false
  .properties.global_settings_oauth:
    selected_option: disabled
    value: disabled
  .properties.global_settings_secure_bindings:
    selected_option: disabled
    value: "No"
  .properties.global_settings_shareable_instances:
    selected_option: disabled
    value: "No"
  .properties.global_settings_si_guid_as_cluster_name:
    value: false
  .properties.metrics_polling_interval:
    value: 30
  .properties.multitenant_support:
    selected_option: disabled
    value: disabled
  .properties.on_demand_broker_plan_1_cf_service_access:
    value: enable
  .properties.on_demand_broker_plan_1_check_queue_sync:
    value: false
  .properties.on_demand_broker_plan_1_description:
    value: This plan provides a single dedicated RabbitMQ node
  .properties.on_demand_broker_plan_1_disk_limit_acknowledgement:
    value:
    - acknowledge
  .properties.on_demand_broker_plan_1_features:
    value: RabbitMQ
  .properties.on_demand_broker_plan_1_instance_quota:
    value: 10
  .properties.on_demand_broker_plan_1_name:
    value: single-node
  .properties.on_demand_broker_plan_1_paid:
    value: false
  .properties.on_demand_broker_plan_1_rabbitmq_az_placement:
    value:
    - ((availability_zone))1
    - ((availability_zone))2
    - ((availability_zone))3
  .properties.on_demand_broker_plan_1_rabbitmq_cluster_partition_handling_strategy:
    value: pause_minority
  .properties.on_demand_broker_plan_1_rabbitmq_number_of_nodes:
    value: 1
  .properties.on_demand_broker_plan_1_service_gateway_enabled:
    value: false
  .properties.on_demand_broker_plan_2_selector:
    selected_option: disabled
    value: disabled
  .properties.on_demand_broker_plan_3_selector:
    selected_option: disabled
    value: disabled
  .properties.on_demand_broker_plan_4_selector:
    selected_option: disabled
    value: disabled
  .properties.on_demand_broker_plan_5_selector:
    selected_option: disabled
    value: disabled
  .properties.on_demand_tls_versions:
    value:
    - tlsv1.3
    - tlsv1.2
network-properties:
  network:
    name: ((networks_services))
  other_availability_zones:
  - name: ((availability_zone))3
  - name: ((availability_zone))2
  - name: ((availability_zone))1
  service_network:
    name: ((networks_services))
  singleton_availability_zone:
    name: ((availability_zone))1
resource-config:
  on-demand-broker:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: automatic
    nsx:
      lbs: []
      security_groups: []
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
  rabbitmq-broker:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: 0
    nsx:
      lbs: []
      security_groups: []
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    swap_as_percent_of_memory_size: automatic
  rabbitmq-haproxy:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: 0
    nsx:
      lbs: []
      security_groups: []
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    swap_as_percent_of_memory_size: automatic
  rabbitmq-server:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: 0
    nsx:
      lbs: []
      security_groups: []
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
errand-config:
  broker-deregistrar:
    pre-delete-state: true
  broker-registrar:
    post-deploy-state: true
  delete-all-service-instances:
    pre-delete-state: true
  deregister-broker:
    pre-delete-state: true
  on-demand-broker-smoke-tests:
    post-deploy-state: true
  recreate-all-service-instances:
    post-deploy-state: false
  register-broker:
    post-deploy-state: true
  smoke-tests:
    post-deploy-state: true
  upgrade-all-service-instances:
    post-deploy-state: true
syslog-properties:
  address: null
  custom_rsyslog_configuration: null
  enabled: false
  forward_debug_logs: false
  permitted_peer: null
  port: null
  queue_size: null
  ssl_ca_certificate: null
  tls_enabled: false
  transport_protocol: tcp