---
product-name: pivotal-container-service
product-properties:
  .pivotal-container-service.pks_tls:
    value:
      cert_pem: ((tkgi_api_cert.certificate))
      private_key_pem: ((tkgi_api_cert.private_key))
  .properties.cloud_provider:
    selected_option: vsphere
    value: vSphere
  .properties.cloud_provider.vsphere.vcenter_dc:
    value: ((vsphere_datacenter))
  .properties.cloud_provider.vsphere.vcenter_ds:
    value: ((vsphere_datastore))
  .properties.cloud_provider.vsphere.vcenter_ip:
    value: ((vsphere_vcenter))
  .properties.cloud_provider.vsphere.vcenter_master_creds:
    value:
      identity: ((vcenter_user.username))
      password: ((vcenter_user.password))
  .properties.cloud_provider.vsphere.vcenter_vms:
    value: ((vsphere_vm_folder))
  .properties.log_sink_resources_deploy:
    value: true
  .properties.metric_sink_resources_deploy:
    value: true
  .properties.network_selector:
    selected_option: nsx
    value: nsx
  .properties.network_selector.nsx.cloud-config-dns:
    value: ((domain_controllers))
  .properties.network_selector.nsx.floating-ip-pool-ids:
    value: ((floating_ip_pool_id))
  .properties.network_selector.nsx.ip-block-id:
    value: ((ip_block_id))
  .properties.network_selector.nsx.nat_mode:
    value: true
  .properties.network_selector.nsx.ncp-ha-heartbeat-period:
    value: 6
  .properties.network_selector.nsx.ncp-ha-master-timeout:
    value: 18
  .properties.network_selector.nsx.ncp-ha-update-timeout:
    value: 12
  .properties.network_selector.nsx.network_automation:
    value: true
  .properties.network_selector.nsx.nodes-ip-block-id:
    value: ((nodes_ip_block_id))
  .properties.network_selector.nsx.nsx-t-ca-cert:
    value: ((nsxt_cert.certificate))
  .properties.network_selector.nsx.nsx-t-host:
    value: ((nsxt_manager_fqdn))
  .properties.network_selector.nsx.nsx-t-insecure:
    value: false
  .properties.network_selector.nsx.nsx-t-superuser-certificate:
    value:
      cert_pem: ((nsxt_superuser_cert.certificate))
      private_key_pem: ((nsxt_superuser_cert.private_key))
  .properties.network_selector.nsx.service_cluster_cidr:
    value: ((service_cluster_cidr)) 
  .properties.network_selector.nsx.t0-router-id:
    value: ((tier0_router))
  .properties.network_selector.nsx.vcenter_cluster:
    value: ((vsphere_cluster))
  .properties.node_exporter_deploy:
    value: false
  .properties.oidc_selector:
    selected_option: enabled
    value: enabled
  .properties.oidc_selector.enabled.groups_claim:
    value: roles
  .properties.oidc_selector.enabled.groups_prefix:
    value: 'oidc:'
  .properties.oidc_selector.enabled.username_claim:
    value: user_name
  .properties.oidc_selector.enabled.username_prefix:
    value: 'oidc:'
  .properties.pks-vrli:
    selected_option: disabled
    value: disabled
  .properties.pks-vrops:
    selected_option: disabled
    value: disabled
  .properties.pks_api_hostname:
    value: ((api_fqdn))
  .properties.plan1_selector:
    selected_option: active
    value: Plan Active
  .properties.plan1_selector.active.admission_plugins:
    value:
    - pod_security_policy
  .properties.plan1_selector.active.allow_privileged_containers:
    value: false
  .properties.plan1_selector.active.description:
    value: 'Example: This plan will configure a lightweight kubernetes cluster. Not
      recommended for production workloads.'
  .properties.plan1_selector.active.kubelet_drain_delete_local_data:
    value: true
  .properties.plan1_selector.active.kubelet_drain_force:
    value: true
  .properties.plan1_selector.active.kubelet_drain_force_node:
    value: false
  .properties.plan1_selector.active.kubelet_drain_grace_period:
    value: 10
  .properties.plan1_selector.active.kubelet_drain_ignore_daemonsets:
    value: true
  .properties.plan1_selector.active.kubelet_drain_timeout:
    value: 0
  .properties.plan1_selector.active.master_az_placement:
    value:
    - ((availability_zone))1
    - ((availability_zone))2
    - ((availability_zone))3
  .properties.plan1_selector.active.master_instances:
    value: 1
  .properties.plan1_selector.active.max_worker_instances:
    value: 50
  .properties.plan1_selector.active.name:
    value: small
  .properties.plan1_selector.active.worker_az_placement:
    value:
    - ((availability_zone))1
    - ((availability_zone))2
    - ((availability_zone))3
  .properties.plan1_selector.active.worker_instances:
    value: 3
  .properties.plan2_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan3_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan4_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan5_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan6_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan7_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan8_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan9_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan10_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan11_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan12_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan13_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.proxy_selector:
    selected_option: disabled
    value: Disabled
  .properties.syslog_selector:
    selected_option: disabled
    value: disabled
  .properties.telegraf_selector:
    selected_option: disabled
    value: disabled
  .properties.telemetry_installation_purpose_selector:
    selected_option: not_provided
    value: not_provided
  .properties.telemetry_selector:
    selected_option: disabled
    value: disabled
  .properties.tmc:
    selected_option: disabled
    value: disabled
  .properties.uaa:
    selected_option: internal
    value: internal
  .properties.uaa_pks_cli_access_token_lifetime:
    value: 600
  .properties.uaa_pks_cli_refresh_token_lifetime:
    value: 21600
  .properties.uaa_pks_cluster_client_access_token_lifetime:
    value: 600
  .properties.uaa_pks_cluster_client_refresh_token_lifetime:
    value: 21600
  .properties.vsphere_csi:
    selected_option: enabled
    value: enabled
  .properties.wavefront:
    selected_option: disabled
    value: disabled
  .properties.worker_max_in_flight:
    value: 4
network-properties:
  network:
    name: ((networks_infrastructure))
  other_availability_zones:
    - name: ((availability_zone))1
    - name: ((availability_zone))2
    - name: ((availability_zone))3
  service_network:
    name: ((networks_services))
  singleton_availability_zone:
    name: ((availability_zone))1
resource-config:
  pivotal-container-service:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: automatic
    nsx:
      lbs: []
      security_groups: []
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
  pks-db:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: automatic
    nsx:
      lbs: []
      security_groups: []
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
errand-config:
  delete-all-clusters:
    pre-delete-state: true
  pks-nsx-t-precheck:
    post-deploy-state: false
  smoke-tests:
    post-deploy-state: false
  upgrade-all-service-instances:
    post-deploy-state: true
