# The following line helps maintain current documentation at http://docs.pivotal.io.
# code_snippet put-resources-pipeline start yaml

# code_snippet resources-pipeline-resource-types start yaml
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest
# code_snippet resources-pipeline-resource-types end yaml

# code_snippet resources-pipeline-products start yaml
resources:
- name: opsman-product
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    endpoint: ((s3_endpoint))
    bucket: ((s3_pivnet_products_bucket))
    region_name: ((s3_region_name))
    secret_access_key: ((s3_secret_access_key))
    regexp: products/\[ops-manager,(.*)\]ops-manager-vsphere.*.ova

- name: tkgi-product
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    endpoint: ((s3_endpoint))
    bucket: ((s3_pivnet_products_bucket))
    region_name: ((s3_region_name))
    secret_access_key: ((s3_secret_access_key))
    regexp: products/\[pivotal-container-service,(.*)\]pivotal-container-service-.*.pivotal

- name: tkgi-stemcell
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    endpoint: ((s3_endpoint))
    bucket: ((s3_pivnet_products_bucket))
    region_name: ((s3_region_name))
    secret_access_key: ((s3_secret_access_key))
    regexp: stemcells/\[stemcells-ubuntu-xenial,(.*)\]bosh-stemcell-.*-vsphere.*\.tgz

- name: antivirus-product
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    endpoint: ((s3_endpoint))
    bucket: ((s3_pivnet_products_bucket))
    region_name: ((s3_region_name))
    secret_access_key: ((s3_secret_access_key))
    regexp: products/\[p-clamav-addon,(.*)\]p-antivirus-.*.pivotal

- name: antivirus-stemcell
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    endpoint: ((s3_endpoint))
    bucket: ((s3_pivnet_products_bucket))
    region_name: ((s3_region_name))
    secret_access_key: ((s3_secret_access_key))
    regexp: stemcells/\[stemcells-ubuntu-xenial,(.*)\]bosh-stemcell-.*-vsphere.*\.tgz

- name: antivirus-mirror-product
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    endpoint: ((s3_endpoint))
    bucket: ((s3_pivnet_products_bucket))
    region_name: ((s3_region_name))
    secret_access_key: ((s3_secret_access_key))
    regexp: products/\[p-clamav-addon,(.*)\]p-antivirus-mirror-.*.pivotal

- name: antivirus-mirror-stemcell
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    endpoint: ((s3_endpoint))
    bucket: ((s3_pivnet_products_bucket))
    region_name: ((s3_region_name))
    secret_access_key: ((s3_secret_access_key))
    regexp: stemcells/\[stemcells-ubuntu-xenial,(.*)\]bosh-stemcell-.*-vsphere.*\.tgz

- name: file-integrety-monitoring-product
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    endpoint: ((s3_endpoint))
    bucket: ((s3_pivnet_products_bucket))
    region_name: ((s3_region_name))
    secret_access_key: ((s3_secret_access_key))
    regexp: products/\[p-fim-addon,(.*)\]p-fim-.*.pivotal

- name: file-integrety-monitoring-stemcell
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    endpoint: ((s3_endpoint))
    bucket: ((s3_pivnet_products_bucket))
    region_name: ((s3_region_name))
    secret_access_key: ((s3_secret_access_key))
    regexp: stemcells/\[stemcells-ubuntu-xenial,(.*)\]bosh-stemcell-.*-vsphere.*\.tgz

- name: compliance-scanner-product
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    endpoint: ((s3_endpoint))
    bucket: ((s3_pivnet_products_bucket))
    region_name: ((s3_region_name))
    secret_access_key: ((s3_secret_access_key))
    regexp: products/\[p-compliance-scanner,(.*)\]p-compliance-scanner-.*.pivotal

- name: compliance-scanner-stemcell
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    endpoint: ((s3_endpoint))
    bucket: ((s3_pivnet_products_bucket))
    region_name: ((s3_region_name))
    secret_access_key: ((s3_secret_access_key))
    regexp: stemcells/\[stemcells-ubuntu-xenial,(.*)\]bosh-stemcell-.*-vsphere.*\.tgz

- name: harbor-registry-product
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    endpoint: ((s3_endpoint))
    bucket: ((s3_pivnet_products_bucket))
    region_name: ((s3_region_name))
    secret_access_key: ((s3_secret_access_key))
    regexp: products/\[harbor-container-registry,(.*)\]harbor-container-registry-.*.pivotal

- name: harbor-registry-stemcell
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    endpoint: ((s3_endpoint))
    bucket: ((s3_pivnet_products_bucket))
    region_name: ((s3_region_name))
    secret_access_key: ((s3_secret_access_key))
    regexp: stemcells/\[stemcells-ubuntu-xenial,(.*)\]bosh-stemcell-.*-vsphere.*\.tgz

- name: healthwatch-product
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    endpoint: ((s3_endpoint))
    bucket: ((s3_pivnet_products_bucket))
    region_name: ((s3_region_name))
    secret_access_key: ((s3_secret_access_key))
    regexp: products/\[p-healthwatch,(.*)\].*.pivotal

- name: healthwatch-stemcell
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    endpoint: ((s3_endpoint))
    bucket: ((s3_pivnet_products_bucket))
    region_name: ((s3_region_name))
    secret_access_key: ((s3_secret_access_key))
    regexp: stemcells/\[stemcells-ubuntu-xenial,(.*)\]bosh-stemcell-.*-vsphere.*\.tgz

- name: tas-product
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    endpoint: ((s3_endpoint))
    bucket: ((s3_pivnet_products_bucket))
    region_name: ((s3_region_name))
    secret_access_key: ((s3_secret_access_key))
    regexp: products/\[elastic-runtime,(.*)\]cf-.*.pivotal

- name: tas-stemcell
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    endpoint: ((s3_endpoint))
    bucket: ((s3_pivnet_products_bucket))
    region_name: ((s3_region_name))
    secret_access_key: ((s3_secret_access_key))
    regexp: stemcells/\[stemcells-ubuntu-xenial,(.*)\]bosh-stemcell-.*-vsphere.*\.tgz
# code_snippet resources-pipeline-products end yaml

- name: nsx-t-product
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    endpoint: ((s3_endpoint))
    bucket: ((s3_pivnet_products_bucket))
    region_name: ((s3_region_name))
    secret_access_key: ((s3_secret_access_key))
    regexp: products/\[vmware-nsx-t,(.*)\]VMware-NSX-T-.*.pivotal

# code_snippet resources-pipeline-platform-automation start yaml
- name: platform-automation-pivnet
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation
    product_version: 5\.(.*)
    sort_by: semver

- name: platform-automation-tasks
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    endpoint: ((s3_endpoint))
    bucket: ((s3_pivnet_products_bucket))
    region_name: ((s3_region_name))
    secret_access_key: ((s3_secret_access_key))
    regexp: platform-automation-tasks-(.*).zip

- name: platform-automation-image
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    endpoint: ((s3_endpoint))
    bucket: ((s3_pivnet_products_bucket))
    region_name: ((s3_region_name))
    secret_access_key: ((s3_secret_access_key))
    regexp: platform-automation-image-(.*).tgz
# code_snippet resources-pipeline-platform-automation end yaml

# code_snippet resources-pipeline-configurations start yaml
- name: configuration
  type: git
  source:
    private_key: ((pipeline-repo-key.private_key))
    uri: ((pipeline-repo-uri))
    branch: master
# code_snippet resources-pipeline-configurations end yaml

# code_snippet resources-pipeline-triggers start yaml
- name: daily
  type: time
  source:
    interval: 24h
# code_snippet resources-pipeline-triggers end yaml

# code_snippet resources-pipeline-prepare-tasks-with-secrets start yaml
# This task is used in multiple jobs
# The yaml anchor "*prepare-tasks-with-secrets" is used in its place
prepare-tasks-with-secrets: &prepare-tasks-with-secrets
  image: platform-automation-image
  file: platform-automation-tasks/tasks/prepare-tasks-with-secrets.yml
  params:
    CONFIG_PATHS: config/download-product-pivnet
    VARS_PATHS: vars/foundations/vars/global.yml
  input_mapping:
    tasks: platform-automation-tasks
    config: configuration
    vars: configuration
  output_mapping:
    tasks: platform-automation-tasks

prepare-image: &prepare-image
  image: platform-automation-image
  file: platform-automation-tasks/tasks/prepare-image.yml
  params:
    CA_CERTS: ((wcf))

# code_snippet resources-pipeline-prepare-tasks-with-secrets end yaml

# code_snippet resources-pipeline-jobs start yaml
jobs:
- name: fetch-opsman
  plan:
  - in_parallel:
    - get: daily
      trigger: true
    - get: platform-automation-image
      params:
        unpack: true
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: configuration
  - task: prepare-image
    <<: *prepare-image
  - task: prepare-tasks-with-secrets
    <<: *prepare-tasks-with-secrets
  - task: download-opsman-image
    image: platform-automation-image
    file: platform-automation-tasks/tasks/download-product.yml
    params:
      CONFIG_FILE: download-product-pivnet/download-opsman.yml
      VARS_FILES: vars/foundations/vars/global.yml
    input_mapping:
      config: configuration
      vars: configuration
  - in_parallel:
    - put: opsman-product
      params:
        file: downloaded-product/*

# code_snippet download-product-usage start yaml
- name: fetch-antivirus
  plan:
  - in_parallel:
    - get: daily
      trigger: true
    - get: platform-automation-image
      params:
        unpack: true
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: configuration
  - task: prepare-image
    <<: *prepare-image
  - task: prepare-tasks-with-secrets
    <<: *prepare-tasks-with-secrets
  - task: download-antivirus-product-and-stemcell
    image: platform-automation-image
    file: platform-automation-tasks/tasks/download-product.yml
    params:
      CONFIG_FILE: download-product-pivnet/download-antivirus.yml
      VARS_FILES: vars/foundations/vars/global.yml
    input_mapping:
      config: configuration
      vars: configuration
    output_mapping: {downloaded-stemcell: antivirus-stemcell}
  - in_parallel:
      - put: antivirus-product
        params:
          file: downloaded-product/*.pivotal
      - put: antivirus-stemcell
        params:
          file: antivirus-stemcell/*.tgz
# code_snippet download-product-usage end

# code_snippet download-product-usage start yaml
- name: fetch-antivirus-mirror
  plan:
  - in_parallel:
    - get: daily
      trigger: true
    - get: platform-automation-image
      params:
        unpack: true
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: configuration
  - task: prepare-image
    <<: *prepare-image
  - task: prepare-tasks-with-secrets
    <<: *prepare-tasks-with-secrets
  - task: download-antivirus-product-and-stemcell
    image: platform-automation-image
    file: platform-automation-tasks/tasks/download-product.yml
    params:
      CONFIG_FILE: download-product-pivnet/download-antivirus-mirror.yml
      VARS_FILES: vars/foundations/vars/global.yml
    input_mapping:
      config: configuration
      vars: configuration
    output_mapping: {downloaded-stemcell: antivirus-mirror-stemcell}
  - in_parallel:
      - put: antivirus-mirror-product
        params:
          file: downloaded-product/*.pivotal
      - put: antivirus-mirror-stemcell
        params:
          file: antivirus-mirror-stemcell/*.tgz
# code_snippet download-product-usage end

# code_snippet download-product-usage start yaml
- name: fetch-file-integrety-monitoring
  plan:
  - in_parallel:
    - get: daily
      trigger: true
    - get: platform-automation-image
      params:
        unpack: true
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: configuration
  - task: prepare-image
    <<: *prepare-image
  - task: prepare-tasks-with-secrets
    <<: *prepare-tasks-with-secrets
  - task: download-antivirus-product-and-stemcell
    image: platform-automation-image
    file: platform-automation-tasks/tasks/download-product.yml
    params:
      CONFIG_FILE: download-product-pivnet/download-fim.yml
      VARS_FILES: vars/foundations/vars/global.yml
    input_mapping:
      config: configuration
      vars: configuration
    output_mapping: {downloaded-stemcell: file-integrety-monitoring-stemcell}
  - in_parallel:
      - put: file-integrety-monitoring-product
        params:
          file: downloaded-product/*.pivotal
      - put: file-integrety-monitoring-stemcell
        params:
          file: file-integrety-monitoring-stemcell/*.tgz
# code_snippet download-product-usage end

# code_snippet download-product-usage start yaml
- name: fetch-compliance-scanner
  plan:
  - in_parallel:
    - get: daily
      trigger: true
    - get: platform-automation-image
      params:
        unpack: true
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: configuration
  - task: prepare-image
    <<: *prepare-image
  - task: prepare-tasks-with-secrets
    <<: *prepare-tasks-with-secrets
  - task: download-antivirus-product-and-stemcell
    image: platform-automation-image
    file: platform-automation-tasks/tasks/download-product.yml
    params:
      CONFIG_FILE: download-product-pivnet/download-compliance-scanner.yml
      VARS_FILES: vars/foundations/vars/global.yml
    input_mapping:
      config: configuration
      vars: configuration
    output_mapping: {downloaded-stemcell: compliance-scanner-stemcell}
  - in_parallel:
      - put: compliance-scanner-product
        params:
          file: downloaded-product/*.pivotal
      - put: compliance-scanner-stemcell
        params:
          file: compliance-scanner-stemcell/*.tgz
# code_snippet download-product-usage end

# code_snippet download-product-usage start yaml
- name: fetch-harbor-registry
  plan:
  - in_parallel:
    - get: daily
      trigger: true
    - get: platform-automation-image
      params:
        unpack: true
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: configuration
  - task: prepare-image
    <<: *prepare-image
  - task: prepare-tasks-with-secrets
    <<: *prepare-tasks-with-secrets
  - task: download-harbor-registry-product-and-stemcell
    image: platform-automation-image
    file: platform-automation-tasks/tasks/download-product.yml
    params:
      CONFIG_FILE: download-product-pivnet/download-harbor-registry.yml
      VARS_FILES: vars/foundations/vars/global.yml
    input_mapping:
      config: configuration
      vars: configuration
    output_mapping: {downloaded-stemcell: harbor-registry-stemcell}
  - in_parallel:
      - put: harbor-registry-product
        params:
          file: downloaded-product/*.pivotal
      - put: harbor-registry-stemcell
        params:
          file: harbor-registry-stemcell/*.tgz
# code_snippet download-product-usage end

# code_snippet download-product-usage start yaml
- name: fetch-healthwatch
  plan:
  - in_parallel:
    - get: daily
      trigger: true
    - get: platform-automation-image
      params:
        unpack: true
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: configuration
  - task: prepare-image
    <<: *prepare-image
  - task: prepare-tasks-with-secrets
    <<: *prepare-tasks-with-secrets
  - task: download-healthwatch-product-and-stemcell
    image: platform-automation-image
    file: platform-automation-tasks/tasks/download-product.yml
    params:
      CONFIG_FILE: download-product-pivnet/download-healthwatch.yml
      VARS_FILES: vars/foundations/vars/global.yml
    input_mapping:
      config: configuration
      vars: configuration
    output_mapping: {downloaded-stemcell: healthwatch-stemcell}
  - in_parallel:
      - put: healthwatch-product
        params:
          file: downloaded-product/*.pivotal
      - put: healthwatch-stemcell
        params:
          file: healthwatch-stemcell/*.tgz
# code_snippet download-product-usage end

# code_snippet download-product-usage start yaml
- name: fetch-tkgi
  plan:
  - in_parallel:
    - get: daily
      trigger: true
    - get: platform-automation-image
      params:
        unpack: true
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: configuration
  - task: prepare-image
    <<: *prepare-image
  - task: prepare-tasks-with-secrets
    <<: *prepare-tasks-with-secrets
  - task: download-tkgi-product-and-stemcell
    image: platform-automation-image
    file: platform-automation-tasks/tasks/download-product.yml
    params:
      CONFIG_FILE: download-product-pivnet/download-tkgi.yml
      VARS_FILES: vars/foundations/vars/global.yml
    input_mapping:
      config: configuration
      vars: configuration
    output_mapping: {downloaded-stemcell: tkgi-stemcell}
  - in_parallel:
      - put: tkgi-product
        params:
          file: downloaded-product/*.pivotal
      - put: tkgi-stemcell
        params:
          file: tkgi-stemcell/*.tgz
# code_snippet download-product-usage end

- name: fetch-tas
  plan:
    - in_parallel:
      - get: daily
        trigger: false
      - get: platform-automation-image
        params:
          unpack: true
      - get: platform-automation-tasks
        params:
          unpack: true
      - get: configuration
    - task: prepare-image
      <<: *prepare-image
    - task: prepare-tasks-with-secrets
      <<: *prepare-tasks-with-secrets
    - task: download-tas-product-and-stemcell
      image: platform-automation-image
      file: platform-automation-tasks/tasks/download-product.yml
      params:
        CONFIG_FILE: download-product-pivnet/download-tas.yml
        VARS_FILES: vars/foundations/vars/global.yml
      input_mapping:
        config: configuration
        vars: configuration
      output_mapping: {downloaded-stemcell: tas-stemcell}
    - in_parallel:
        - put: tas-product
          params:
            file: downloaded-product/*.pivotal
        - put: tas-stemcell
          params:
            file: tas-stemcell/*.tgz

- name: fetch-nsx-t
  plan:
    - in_parallel:
      - get: daily
        trigger: true
      - get: platform-automation-image
        params:
          unpack: true
      - get: platform-automation-tasks
        params:
          unpack: true
      - get: configuration
    - task: prepare-image
      <<: *prepare-image
    - task: prepare-tasks-with-secrets
      <<: *prepare-tasks-with-secrets
    - task: download-nsx-t-product
      image: platform-automation-image
      file: platform-automation-tasks/tasks/download-product.yml
      params:
        CONFIG_FILE: download-product-pivnet/download-nsx-t.yml
        VARS_FILES: vars/foundations/vars/global.yml
      input_mapping:
        config: configuration
        vars: configuration
    - in_parallel:
      - put: nsx-t-product
        params:
          file: downloaded-product/*.pivotal

- name: fetch-platform-automation
  # We use the pivnet resource to bootstrap the pipeline,
  # and because this product is part of the pipeline, not the foundation
  plan:
  - get: platform-automation-pivnet
    trigger: true
  - in_parallel:
    - put: platform-automation-tasks
      params:
        file: platform-automation-pivnet/*tasks*.zip
    - put: platform-automation-image
      params:
        file: platform-automation-pivnet/*image*.tgz
# code_snippet resources-pipeline-jobs end yaml
# code_snippet put-resources-pipeline end
# The previous line helps maintain current documentation at http://docs.pivotal.io.
