---
product-name: appMetrics
product-properties:
  .db-and-errand-runner.enable_logs:
    value: true
  .db-and-errand-runner.postgres_ciphers:
    value: HIGH:MEDIUM:+3DES:!aNULL
  .db-and-errand-runner.use_socks_proxy:
    value: false
  .log-store-vms.log_store_partition_count:
    value: 64
  .log-store-vms.log_store_prune_interval:
    value: 2m
  .log-store-vms.log_store_prune_threshold:
    value: 80
  .log-store-vms.log_store_retention_period:
    value: 42
network-properties:
  network:
    name: ((networks_services))
  other_availability_zones:
  - name: DEV-AZ3
  - name: DEV-AZ2
  - name: DEV-AZ1
  singleton_availability_zone:
    name: DEV-AZ1
resource-config:
  db-and-errand-runner:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: automatic
    nsx:
      lbs: []
      security_groups: []
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
  log-store-vms:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: automatic
    nsx:
      lbs: []
      security_groups: []
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
errand-config:
  delete-space:
    pre-delete-state: true
  migrate-route:
    post-deploy-state: true
  push-app-metrics:
    post-deploy-state: true
  smoke-test:
    post-deploy-state: true
syslog-properties:
  address: null
  custom_rsyslog_configuration: null
  enabled: false
  forward_debug_logs: false
  permitted_peer: null
  port: null
  queue_size: null
  ssl_ca_certificate: null
  tls_enabled: false
  transport_protocol: tcp