---
product-name: metric-store
product-properties:
  .properties.max_concurrent_queries:
    value: 1
  .properties.replication_factor:
    value: 2
network-properties:
  network:
    name: ((networks_services))
  other_availability_zones:
  - name: ((availability_zone))3
  - name: ((availability_zone))2
  - name: ((availability_zone))1
  singleton_availability_zone:
    name: ((availability_zone))1
resource-config:
  metric-store:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: automatic
    nsx:
      lbs: []
      security_groups: []
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
syslog-properties:
  address: null
  custom_rsyslog_configuration: null
  enabled: false
  forward_debug_logs: false
  permitted_peer: null
  port: null
  queue_size: null
  ssl_ca_certificate: null
  tls_enabled: false
  transport_protocol: tcp